#!/bin/bash

set -o errexit
set -o nounset

TAG_FILE='.tags'

[ -e "$TAG_FILE" ] && rm "$TAG_FILE"

ctags \
    -I '__THROW' \
    '--extras=+F' \
    '--langmap=c:+.h' \
    '--languages=c,c++' \
    '--links=yes' \
    '--c-kinds=+p' \
    '--fields=+S' \
    -f "$TAG_FILE" \
    -R \
    src \
    '/usr/include/luajit-2.1' \
    '/usr/include/git2' \
    '/usr/include/git2.h'
